name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  go_router: ^13.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/dishes/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/sen/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sen/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/sen/Sen-Regular.ttf
          weight: 400
    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
